// next-env.d.ts (which normally provides this reference) is gitignored and
// only gets regenerated by `next dev`/`next build` — CI's `tsc --noEmit`
// step runs neither first, so a fresh checkout has no image-import type
// declarations (`import logo from "./logo.png"` etc) without this checked-in
// copy of the same reference. See Wordmark.tsx for the import that needs it.
/// <reference types="next/image-types/global" />
